"""Parse the local AMAPI catalog page to extract the authoritative function inventory.

Usage:
    python scripts/amapi_crawler_parse_api_index.py

Reads: assets/air_manager_api/wiki.siminnovations.com/index.php@title=API
Writes: docs/knowledge/amapi_function_inventory.md
"""
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from amapi_crawler_lib.normalize import normalize, title_from_url

try:
    from bs4 import BeautifulSoup
except ImportError:
    print("ERROR: beautifulsoup4 not installed. Run: pip install beautifulsoup4")
    sys.exit(1)

CATALOG_PATH = Path("assets/air_manager_api/wiki.siminnovations.com/index.php@title=API")
DB_PATH = Path("assets/air_manager_api/crawl.sqlite3")
INVENTORY_PATH = Path("docs/knowledge/amapi_function_inventory.md")
BASE_URL = "https://wiki.siminnovations.com"


def extract_links(html: str) -> list[tuple[str, str]]:
    """Return (url, anchor_text) pairs for wiki-internal links in article body."""
    soup = BeautifulSoup(html, "html.parser")
    content = soup.find(id="mw-content-text")
    if not content:
        return []

    results = []
    for a in content.find_all("a", href=True):
        href = a["href"]
        classes = a.get("class", [])
        # Skip redlinks (class="new") and explicit redlink= hrefs
        if "new" in classes:
            continue
        if "redlink=1" in href:
            continue
        # Only wiki-internal page links
        if href.startswith("/index.php?title=") or href.startswith("/index.php/"):
            full_url = BASE_URL + href
            results.append((full_url, a.get_text(strip=True)))
    return results


def main() -> None:
    html = CATALOG_PATH.read_text(encoding="utf-8", errors="replace")
    raw_links = extract_links(html)

    # Normalize and deduplicate; build title → normalized_url mapping
    seen: dict[str, tuple[str, str]] = {}  # title → (norm_url, anchor_text)
    for raw_url, anchor in raw_links:
        norm = normalize(raw_url)
        if norm is None:
            continue
        title = title_from_url(norm)
        if title is None:
            continue
        if title not in seen:
            seen[title] = (norm, anchor)

    # Group by first-underscore prefix
    by_prefix: dict[str, list[str]] = defaultdict(list)
    unprefixed: list[str] = []
    for title in sorted(seen):
        if "_" in title:
            prefix = title.split("_")[0]
            by_prefix[prefix].append(title)
        else:
            unprefixed.append(title)

    # Print summary to stdout
    print("=" * 60)
    print("PREFIXES FOUND ON API CATALOG PAGE")
    print("=" * 60)
    for prefix, titles in sorted(by_prefix.items()):
        print(f"  {prefix:<30} {len(titles):>3} function(s)")

    print()
    print("=" * 60)
    print("UNPREFIXED FUNCTION TITLES (no underscore)")
    print("=" * 60)
    for t in sorted(unprefixed):
        print(f"  {t}")

    # DB join to check fetch status
    con = sqlite3.connect(str(DB_PATH))
    def db_status(url: str) -> tuple[str, str]:
        row = con.execute(
            "SELECT status, category FROM urls WHERE url = ?", (url,)
        ).fetchone()
        if row:
            return row[0], row[1] or ""
        return "not_in_db", ""

    all_titles = sorted(seen)

    # ── Generate inventory markdown ──────────────────────────────────────────
    lines = [
        "---",
        "Created: 2026-04-20T00:00:00-04:00",
        "Source: docs/tasks/amapi_crawler_bugfix_03_prompt.md",
        "---",
        "",
        "# AMAPI Function Inventory",
        "",
        "Generated by: scripts/amapi_crawler_parse_api_index.py",
        "Source page: index.php?title=API (local mirror)",
        "",
        "## Prefixed API functions",
        "",
        "| Title | First-token prefix | Fetched? | Category |",
        "| --- | --- | --- | --- |",
    ]
    for title in sorted(seen):
        if "_" not in title:
            continue
        norm_url, _ = seen[title]
        status, cat = db_status(norm_url)
        fetched = "Y" if status == "fetched" else "N"
        prefix = title.split("_")[0]
        lines.append(f"| {title} | {prefix} | {fetched} | {cat} |")

    lines += [
        "",
        "## Unprefixed API functions",
        "",
        "| Title | Fetched? | Category |",
        "| --- | --- | --- |",
    ]
    for title in sorted(unprefixed):
        norm_url, _ = seen[title]
        status, cat = db_status(norm_url)
        fetched = "Y" if status == "fetched" else "N"
        lines.append(f"| {title} | {fetched} | {cat} |")

    # ── Whitelist additions ───────────────────────────────────────────────────
    from amapi_crawler_lib.categorize import API_PREFIXES

    new_prefixes = sorted(p for p in by_prefix if p not in API_PREFIXES)
    new_unprefixed = sorted(unprefixed)  # all listed; caller decides which to add

    lines += [
        "",
        "## Whitelist Additions (Phase A)",
        "",
        "### Category 1 — New prefixes (to add to API_PREFIXES)",
        "",
        "| Prefix | Functions on catalog page |",
        "| --- | --- |",
    ]
    for p in new_prefixes:
        funcs = ", ".join(by_prefix[p])
        lines.append(f"| {p} | {funcs} |")

    lines += [
        "",
        "### Category 2 — Unprefixed API functions (to add to UNPREFIXED_API_FUNCTIONS)",
        "",
        "| Title | Notes |",
        "| --- | --- |",
    ]
    for t in new_unprefixed:
        lines.append(f"| {t} | canvas draw callback |")

    lines.append("")
    con.close()

    INVENTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nInventory written to {INVENTORY_PATH}")
    print(f"\nTotal unique titles on catalog page: {len(all_titles)}")
    print(f"  Prefixed: {sum(len(v) for v in by_prefix.values())}")
    print(f"  Unprefixed: {len(unprefixed)}")
    print(f"\nCategory 1 — New prefixes not in current API_PREFIXES ({len(new_prefixes)}):")
    for p in new_prefixes:
        print(f"  {p}: {by_prefix[p]}")
    print(f"\nCategory 2 — Unprefixed functions ({len(new_unprefixed)}): {new_unprefixed}")


if __name__ == "__main__":
    main()
